###
# Get agents
###

GET http://localhost:5042/api/agents


###
# Disable agent
###

PUT http://localhost:5042/api/agents/coldTurkey/toggle

###
# Refresh
###

PUT http://localhost:5042/api/agents/refresh


# steward/agents/register
{
    "version": "0.1.0",
    "agentId": "test-agent",
    "instanceId": "abc123",
    "name": "Test Agent",
    "devices": [
        {
            "deviceId": "desktop",
            "name": "Gaming PC"
        },
        {
            "deviceId": "laptop",
            "name": "Work Laptop"
        }
    ],
    "resources": [
        {
            "resourceId": "youtube",
            "name": "YouTube"
        },
        {
            "resourceId": "reddit",
            "name": "Reddit"
        }
    ]
}
