// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Steward.Server.Data;

#nullable disable

namespace Steward.Server.Migrations
{
    [DbContext(typeof(StewardDbContext))]
    [Migration("20260806171529_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Steward.Server.Data.Entities.AgentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.AgentStatusEntity", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AgentId");

                    b.ToTable("AgentStatuses");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.PolicyAccessEntity", b =>
                {
                    b.Property<int>("PolicyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("LastAccessed")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutesUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnlocksUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("PolicyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PolicyAccess");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.PolicyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WardId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.ResourceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.UserDeviceEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardDeviceEntity", b =>
                {
                    b.Property<int>("WardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WardId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("WardDevices");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardResourceEntity", b =>
                {
                    b.Property<int>("WardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WardId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("WardResources");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardUserEntity", b =>
                {
                    b.Property<int>("WardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WardId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WardUsers");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.AgentStatusEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.AgentEntity", "Agent")
                        .WithOne("Status")
                        .HasForeignKey("Steward.Server.Data.Entities.AgentStatusEntity", "AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.DeviceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.AgentEntity", "Agent")
                        .WithMany("Devices")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.PolicyAccessEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.PolicyEntity", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steward.Server.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.PolicyEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.WardEntity", "Ward")
                        .WithMany("Policies")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Steward.Server.Data.Policies.Allowance", "Access", b1 =>
                        {
                            b1.Property<int>("PolicyEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DailyTimeMinutes")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DailyUnlocks")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("MaxSessionMinutes")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PolicyEntityId");

                            b1.ToTable("Policies");

                            b1.WithOwner()
                                .HasForeignKey("PolicyEntityId");
                        });

                    b.OwnsOne("Steward.Server.Data.Policies.OverridePolicy", "Override", b1 =>
                        {
                            b1.Property<int>("PolicyEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Allowed")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Requirement")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PolicyEntityId");

                            b1.ToTable("Policies");

                            b1.WithOwner()
                                .HasForeignKey("PolicyEntityId");

                            b1.OwnsOne("Steward.Server.Data.Policies.Allowance", "Allowance", b2 =>
                                {
                                    b2.Property<int>("OverridePolicyPolicyEntityId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("DailyTimeMinutes")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("DailyUnlocks")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int?>("MaxSessionMinutes")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("OverridePolicyPolicyEntityId");

                                    b2.ToTable("Policies");

                                    b2.WithOwner()
                                        .HasForeignKey("OverridePolicyPolicyEntityId");
                                });

                            b1.Navigation("Allowance")
                                .IsRequired();
                        });

                    b.OwnsOne("Steward.Server.Data.Policies.Schedule", "Schedule", b1 =>
                        {
                            b1.Property<int>("PolicyEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Days")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("PolicyEntityId");

                            b1.ToTable("Policies");

                            b1.WithOwner()
                                .HasForeignKey("PolicyEntityId");
                        });

                    b.Navigation("Access")
                        .IsRequired();

                    b.Navigation("Override")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.ResourceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.AgentEntity", "Agent")
                        .WithMany("Resources")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.UserDeviceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steward.Server.Data.Entities.UserEntity", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardDeviceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steward.Server.Data.Entities.WardEntity", "Ward")
                        .WithMany("Devices")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardResourceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steward.Server.Data.Entities.WardEntity", "Ward")
                        .WithMany("Resources")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardUserEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steward.Server.Data.Entities.WardEntity", "Ward")
                        .WithMany("Users")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.AgentEntity", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Resources");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardEntity", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Policies");

                    b.Navigation("Resources");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
