// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Steward.Server.Data;

#nullable disable

namespace Steward.Server.Migrations
{
    [DbContext(typeof(StewardDbContext))]
    partial class StewardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Steward.Server.Data.Entities.AgentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "InstanceId")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.ResourceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.UserDeviceEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("UserDeviceEntity");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardDeviceEntity", b =>
                {
                    b.Property<string>("WardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.HasKey("WardId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("WardDevices");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardResourceEntity", b =>
                {
                    b.Property<string>("WardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("WardId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("WardResources");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardUserEntity", b =>
                {
                    b.Property<string>("WardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("WardId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WardUsers");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.DeviceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.AgentEntity", "Agent")
                        .WithMany("Devices")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.ResourceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.AgentEntity", "Agent")
                        .WithMany("Resources")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.UserDeviceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steward.Server.Data.Entities.UserEntity", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardDeviceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steward.Server.Data.Entities.WardEntity", "Ward")
                        .WithMany("Devices")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardResourceEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steward.Server.Data.Entities.WardEntity", "Ward")
                        .WithMany("Resources")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardUserEntity", b =>
                {
                    b.HasOne("Steward.Server.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steward.Server.Data.Entities.WardEntity", "Ward")
                        .WithMany("Users")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.AgentEntity", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("Steward.Server.Data.Entities.WardEntity", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Resources");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
